"""Generate + validate the obligation/disbursement ICD from factory artifacts.

Usage:
    python generate_icd.py [--out-dir generated] [--date YYYY-MM-DD]

Emits three artifacts into ``--out-dir``:

    ICD-OBL-DISBURSEMENT.json   the structured document (machine-readable)
    ICD-OBL-DISBURSEMENT.md     readable Markdown rendering
    icd.data.js                 data file consumed by the portfolio dashboard

Exit code is non-zero if the generated ICD violates the customer's spec
(``validate.validate_icd``), so this doubles as a CI gate — the same pattern
as the conversion slices.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from icd_builder import build_obligation_disbursement_icd
from validate import validate_icd


def _table(rows: list[dict], columns: list[str]) -> str:
    head = "| " + " | ".join(columns) + " |"
    sep = "| " + " | ".join("---" for _ in columns) + " |"
    body = []
    for row in rows:
        cells = []
        for col in columns:
            val = row.get(col, "")
            if isinstance(val, list):
                val = ", ".join(str(x) for x in val)
            cells.append(str(val).replace("|", "\\|"))
        body.append("| " + " | ".join(cells) + " |")
    return "\n".join([head, sep, *body])


def _bullets(items: list) -> str:
    return "\n".join(f"- {i}" for i in items)


def render_markdown(icd: dict) -> str:
    tp = icd["title_page"]
    es = icd["executive_summary"]
    parts = [
        f"> {tp['classification_banner']}",
        "",
        f"# Interface Control Document — {tp['interface_name']}",
        "",
        f"*Document date: {tp['document_date']} — generated by the Integration & Conversion Factory "
        "from the slice's live code, contracts, and reconciliation artifacts; structure per the "
        "customer ICD automation spec (`factory/reference/customer-artifacts/icd_schema.json`).*",
        "",
        "## Version Tracker",
        _table(icd["versions"], ["sequence_number", "status", "author", "date", "change_summary"]),
        "",
        "## Executive Summary",
        f"**Business context.** {es['business_context']}",
        "",
        f"**Integration objective.** {es['integration_objective']}",
        "",
        f"**Stakeholders.** {es['stakeholder_summary']}",
        "",
        "## 1. Introduction",
        f"**1.2 Purpose.** {icd['purpose_statement']}",
        "",
        "**1.3 Scope — in scope:**",
        _bullets(icd["in_scope_items"]),
        "",
        "**Out of scope:**",
        _bullets(icd["out_of_scope_items"]),
        "",
        "**1.4 Assumptions:**",
        _bullets(icd["assumptions"]),
        "",
        "**1.5 Constraints:**",
        _bullets(icd["constraints"]),
        "",
        "**1.6 Acknowledgements:**",
        _table(icd["acknowledgements"], ["item", "proposed_resolution"]),
        "",
        "**1.7 Points of Contact:**",
        _table(icd["pocs"], ["name", "email", "position", "organization"]),
        "",
        f"**1.8 Wave:** {icd['wave_label']}",
        "",
        "**1.9 Terminology:**",
        _table(icd["terms"], ["term", "definition"]),
        "",
        f"**1.10 Operational agreement.** {icd['operational_agreement_text']}",
        "",
        "**1.11 References:**",
        _table(icd["references"], ["title", "relevance"]),
        "",
        "## 2. System Identification",
        f"**2.1 VA system — {icd['va_system']['system_name']}.** "
        f"{icd['va_system']['system_function_summary']} {icd['va_system']['technical_platform_summary']}",
        "",
        f"**2.2 iFAMS.** {icd['ifams_systems']['ifams_functions_summary']} ESB functions:",
        _bullets(icd["ifams_systems"]["esb_functions"]),
        "",
        "## 3. Interface Definition",
        f"**3.1 Legacy integration.** {icd['legacy_process_description']}",
        "",
        f"**3.2 Future integration.** {icd['future_process_description']}",
        "",
        "**3.3.1 Operations:**",
        _table(icd["operations"], ["id", "name", "purpose", "trigger", "direction", "interfaces_impacted"]),
        "",
        "**3.3.2 Data transfer:**",
        _table(icd["transfer_mechanisms"], ["protocol", "routing", "packaging"]),
        "",
        "**3.3.3 Transaction types:**",
        _table(icd["transaction_types"], ["name", "usage", "frequency", "volume_estimate"]),
        "",
        "**3.3.4 Data exchanges:**",
        _table(icd["data_exchanges"], ["producer", "consumer", "format", "schedule", "acknowledgement"]),
        "",
        f"**3.3.5 Data compliance.** {icd['data_compliance']['compliance_strategy']}",
        "",
        "**3.3.6 Precedence:**",
        _bullets(icd["precedence_rules"]),
        "",
        "**Criticality:**",
        _bullets(icd["criticality_levels"]),
        "",
        "**3.3.7 Communication methods:**",
        _bullets(icd["comm_methods"]),
        "",
        "**3.3.8 Security & integrity:**",
        _table(icd["security_requirements"], ["id", "requirement", "implementation_detail", "transmission_medium", "data_protection", "auditability"]),
        "",
        "**3.3.9 Logging & audit:**",
        _table(icd["logging_by_platform"], ["platform", "logging_detail", "audit_detail", "poc", "monitoring_instructions"]),
        "",
        "## 4. Operational Considerations",
        "**4.1 Data volumes:**",
        _table(icd["volume_matrix"], ["service_name", "transaction_volume", "line_counts", "hours_of_operation", "frequency"]),
        "",
        "**Peak periods:**",
        _bullets(icd["peak_periods"]),
        "",
        f"**4.2 Data contention.** {icd['contention_analysis']} Mitigations:",
        _bullets(icd["mitigations"]),
        "",
        "**4.3 Performance requirements:**",
        _table(icd["performance_requirements"], ["id", "requirement_text", "metric", "threshold", "measurement_method"]),
        "",
        "**4.4 Priorities:** " + "; ".join(icd["priorities"]),
        "",
        "**Dependencies:** " + "; ".join(icd["dependencies"]),
        "",
        "**4.5 Service availability:**",
        _table(icd["availability_matrix"], ["system", "availability", "maintenance_window", "scheduled_outage_process"]),
        "",
        "**4.6 Scheduling & operations (runbook):**",
        _table(icd["runbook_entries"], ["job_name", "schedule", "preconditions", "file_locations", "expected_counts", "escalation_steps"]),
        "",
        "**4.7 Upgrades / future waves:**",
        _table(icd["upgrade_topics"], ["area", "impact", "action_required"]),
        "",
        "## 5. Error Handling & Reconciliation",
        "**5.1 Error handling:**",
        _table(icd["error_handling_matrix"], ["service_name", "platform", "detection_method", "common_error_codes", "correction_process", "resubmission_method", "responsible_team"]),
        "",
        "**5.2 Reconciliation:**",
        _table(icd["recon_strategies"], ["scope", "control_totals_used", "reports", "frequency", "owner"]),
        "",
        "**5.3 Troubleshooting:**",
        _table(icd["troubleshooting_entries"], ["symptom", "probable_cause", "steps_to_resolve", "escalation_contact"]),
        "",
        "## 6. Interface Requirements",
        "**6.1 Message exchanges:**",
        _table(icd["message_exchanges"], ["id", "name", "direction", "format", "trigger", "acknowledgement", "success_criteria"]),
        "",
        f"**6.2 File mapping** ({len(icd['file_mapping'])} fields, generated from the contract dataclass):",
        _table(icd["file_mapping"], ["position", "system_field_name", "ifams_field_name", "description", "ifams_table_field", "max_length", "format"]),
        "",
        f"**6.3 Web-service mapping.** {icd['ws_mapping_note']}",
        "",
        "## 7. Interface Verification",
        _table(icd["verification_methods"], ["method", "success_criteria"]),
        "",
        "## 8. Interface Controls",
        _table(icd["controls"], ["control_id", "control_activity", "control_technique", "implementation_detail"]),
        "",
        "## 9. Implementation & Cutover",
        f"**9.1 Conversion considerations.** {icd['conversion_considerations']['conversion_notes']} "
        f"Converted-data interactions: {icd['conversion_considerations']['converted_data_interactions']}",
        "",
        "**9.2 Transition approach:**",
        _bullets(icd["transition_steps"]),
        "",
        f"**Rollback.** {icd['rollback_plan']}",
        "",
        "## 10. Test Scripts",
        _table(icd["test_scripts"], ["id", "name", "description"]),
        "",
        "## 11. Open Items",
        _table(icd["open_items"], ["number", "status", "description", "impact"]),
        "",
        "## Appendix A — Requirements Traceability",
        _table(icd["features"], ["feature_id", "description", "acceptance_criteria", "requirement_locations", "team_impact", "implemented_by"]),
        "",
        "## Appendix B — ICD Metrics",
        _table([icd["metrics"]], list(icd["metrics"].keys())),
        "",
        "## Appendix D — New Environment Connect",
        _bullets(icd["environment_connect_steps"]),
        "",
    ]
    return "\n".join(parts)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", default=str(Path(__file__).parent / "generated"))
    parser.add_argument("--date", default=None, help="document date YYYY-MM-DD")
    args = parser.parse_args(argv)

    icd = build_obligation_disbursement_icd(document_date=args.date)
    violations = validate_icd(icd)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "ICD-OBL-DISBURSEMENT.json").write_text(json.dumps(icd, indent=2) + "\n")
    (out_dir / "ICD-OBL-DISBURSEMENT.md").write_text(render_markdown(icd))
    (out_dir / "icd.data.js").write_text("window.ICD_DATA = " + json.dumps(icd, indent=2) + ";\n")

    n_fields = len(icd["file_mapping"])
    n_controls = len(icd["controls"])
    print(f"[generate_icd] sections rendered; file mapping fields: {n_fields}; controls: {n_controls}")
    if violations:
        print(f"[generate_icd] SPEC VIOLATIONS ({len(violations)}):")
        for item in violations:
            print(f"  - {item}")
        return 1
    print("[generate_icd] spec validation: PASS (0 violations against customer ICD schema)")
    print(f"[generate_icd] wrote {out_dir}/ICD-OBL-DISBURSEMENT.{{json,md}} and icd.data.js")
    return 0


if __name__ == "__main__":
    sys.exit(main())
