"""S8 knowledge-fabric learning loop — live demo.

This script demonstrates the factory's feedback loop: a first conversion pass
rejects records because the reference data (USSGL whitelist + fund crosswalk) is
incomplete; an SME confirms those rejects are *valid postings the chart was
simply missing*; the knowledge fabric is updated; and a second pass over the
**same input** now accepts them. Reject count drops, mapping coverage rises, and
the knowledge fabric grows — all provable, no hand-waving.

It runs against the existing GL/journal slice (no new conversion code): it
imports that slice's `convert.run_slice` and `mapper`, and injects reference data
by replacing the mapper's module-level `USSGL_WHITELIST` and `FUND_CROSSWALK`
(which `map_line` reads at call time). That is exactly how the real factory treats
the knowledge fabric — as injected context, not hard-coded constants.

Honesty note: the "SME confirmation" here is a small scripted resolution table
(`SME_RESOLUTIONS`) standing in for a human analyst clearing the reject queue.
The *loop* is real; the human-in-the-loop decision is simulated so the demo is
deterministic and re-runnable.

Run:
    python run_learning_demo.py            # human-readable before/after
    python run_learning_demo.py --json     # machine-readable summary

Re-running is idempotent: the demo resets its working knowledge to the committed
seed (`knowledge/base-reference-data.json`) and rewrites the managed block in
`factory/knowledge/reject-taxonomy.md` between its markers each time.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[2]
GL_PYTHON = REPO_ROOT / "factory" / "conversion-datasets" / "gl-journal-extract" / "python"
TAXONOMY = REPO_ROOT / "factory" / "knowledge" / "reject-taxonomy.md"

BASE_REFERENCE = HERE / "knowledge" / "base-reference-data.json"
LEARNED_REFERENCE = HERE / "knowledge" / "learned-reference-data.json"
LEARNING_FIXTURE = HERE / "data" / "gl_extract_learning.dat"

LEARN_BEGIN = "<!-- BEGIN LEARNED (auto-generated by run_learning_demo.py — do not edit by hand) -->"
LEARN_END = "<!-- END LEARNED -->"

# Make the GL slice importable as flat modules (convert, mapper, ...).
sys.path.insert(0, str(GL_PYTHON))

import convert  # noqa: E402  (import after sys.path edit)
import mapper  # noqa: E402

# --- SME resolution table --------------------------------------------------
# What a human analyst confirms when they work the reject queue for THIS batch.
# In production this is the SME's decision captured in the review UI / Git; here
# it is scripted so the demo is deterministic. Each entry says "this rejected
# value is actually valid — add it to the reference data with this meaning."
SME_RESOLUTIONS = {
    "fund_crosswalk": {
        # Legacy fund 8180 = VA General Post Fund (a real VA trust fund, 36X8180);
        # it simply was not in the seed crosswalk.
        "8180": "8180-GPF",
    },
    "ussgl_whitelist": {
        # USSGL 490200 = Delivered Orders - Obligations, Paid. The obligation/
        # disbursement slice already knows this account; the loop teaches the GL
        # slice the same thing — knowledge learned on one interface generalizes.
        "490200": "Delivered Orders - Obligations, Paid",
    },
}


def build_learning_fixture() -> None:
    """Write the synthetic GL variant fixture using the GL slice's own builders.

    Three balanced journals, so that once the gaps are learned every journal
    balances and the batch becomes load-ready:

      JV 700  uses unmapped legacy fund 8180        -> BAD_FUND on both lines
      JV 701  uses unmapped USSGL 490200 (debit)    -> BAD_USSGL on the debit line
      JV 702  uses only already-known reference data -> accepted in both passes
    """
    sys.path.insert(0, str(GL_PYTHON))
    from make_synthetic_data import cents, rec  # noqa: E402

    lines = [
        # JV 700 — both lines on fund 8180 (missing from seed crosswalk).
        rec(jv="000700", line="001", drcr="D", ussgl="480100", fund="8180",
            tafs="036-2026-8180-000", amount_cents=cents(50000),
            desc="UDO - GEN POST FUND GRANT"),
        rec(jv="000700", line="002", drcr="C", ussgl="211000", fund="8180",
            tafs="036-2026-8180-000", amount_cents=cents(50000),
            desc="ACCOUNTS PAYABLE - GPF GRANT"),
        # JV 701 — debit line on USSGL 490200 (missing from seed whitelist).
        rec(jv="000701", line="001", drcr="D", ussgl="490200", fund="0160",
            amount_cents=cents(25000), desc="DELIVERED ORDERS PAID"),
        rec(jv="000701", line="002", drcr="C", ussgl="211000", fund="0160",
            amount_cents=cents(25000), desc="ACCOUNTS PAYABLE - DOP"),
        # JV 702 — fully known; a control that stays accepted across both passes.
        rec(jv="000702", line="001", drcr="D", ussgl="480100", fund="0160",
            amount_cents=cents(10000), desc="UDO - OFFICE SUPPLIES"),
        rec(jv="000702", line="002", drcr="C", ussgl="211000", fund="0160",
            amount_cents=cents(10000), desc="ACCOUNTS PAYABLE - SUPPLIES"),
    ]
    LEARNING_FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    LEARNING_FIXTURE.write_text("\n".join(lines) + "\n")


def load_reference(path: Path) -> dict:
    return json.loads(path.read_text())


def apply_reference(ref: dict) -> None:
    """Inject reference data into the GL mapper (the knowledge fabric as context)."""
    mapper.USSGL_WHITELIST = frozenset(ref["ussgl_whitelist"])
    mapper.FUND_CROSSWALK = dict(ref["fund_crosswalk"])


def run_pass(label: str) -> dict:
    report, wire = convert.run_slice(LEARNING_FIXTURE.read_text())
    return {
        "label": label,
        "lines_in": report.lines_in,
        "accepted": len(report.accepted),
        "rejected": len(report.rejected),
        "reject_reasons": report.reject_reasons,
        "mapping_coverage": report.mapping_coverage,
        "all_journals_balanced": report.all_journals_balanced,
        "load_ready": report.load_ready,
        "wire_count": len(wire),
    }


def grow_knowledge(seed: dict, first_pass: dict) -> dict:
    """Apply SME resolutions for the reject reasons we actually saw.

    Only learns corrections for patterns that genuinely appeared in pass 1, so
    the demo can never "learn" something it didn't observe.
    """
    learned = {
        "ussgl_whitelist": list(seed["ussgl_whitelist"]),
        "fund_crosswalk": dict(seed["fund_crosswalk"]),
    }
    additions = {"fund_crosswalk": {}, "ussgl_whitelist": {}}

    reasons = first_pass["reject_reasons"]
    if reasons.get("BAD_FUND"):
        for code, momentum_fund in SME_RESOLUTIONS["fund_crosswalk"].items():
            if code not in learned["fund_crosswalk"]:
                learned["fund_crosswalk"][code] = momentum_fund
                additions["fund_crosswalk"][code] = momentum_fund
    if reasons.get("BAD_USSGL"):
        for acct, meaning in SME_RESOLUTIONS["ussgl_whitelist"].items():
            if acct not in learned["ussgl_whitelist"]:
                learned["ussgl_whitelist"].append(acct)
                additions["ussgl_whitelist"][acct] = meaning

    learned["ussgl_whitelist"] = sorted(set(learned["ussgl_whitelist"]))
    LEARNED_REFERENCE.write_text(json.dumps(learned, indent=2) + "\n")
    return additions


def update_taxonomy(additions: dict) -> int:
    """Rewrite the managed LEARNED block in reject-taxonomy.md. Returns lines added."""
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    rows = []
    for acct, meaning in sorted(additions["ussgl_whitelist"].items()):
        rows.append(
            f"| `BAD_USSGL` | `{acct}` | Valid USSGL account ({meaning}) missing "
            f"from the GL slice whitelist. | Added to whitelist; line now posts. |"
        )
    for code, momentum_fund in sorted(additions["fund_crosswalk"].items()):
        rows.append(
            f"| `BAD_FUND` | legacy fund `{code}` | Valid VA fund missing from the "
            f"crosswalk. | Mapped to Momentum fund `{momentum_fund}`; line now posts. |"
        )

    if rows:
        body = (
            f"_Last run: {stamp}. The S8 loop resolved "
            f"{len(rows)} reject pattern(s) by extending the reference data._\n\n"
            "| Original reject | Pattern | SME finding | Resolution |\n"
            "| --- | --- | --- | --- |\n" + "\n".join(rows) + "\n"
        )
    else:
        body = (
            f"_Last run: {stamp}. No new reject patterns required a correction._\n"
        )

    text = TAXONOMY.read_text()
    pre, _, rest = text.partition(LEARN_BEGIN)
    _, _, post = rest.partition(LEARN_END)
    new_text = f"{pre}{LEARN_BEGIN}\n{body}{LEARN_END}{post}"
    TAXONOMY.write_text(new_text)
    return len(rows)


def render(seed: dict, learned: dict, p1: dict, p2: dict, learned_rows: int) -> str:
    seed_count = len(seed["ussgl_whitelist"]) + len(seed["fund_crosswalk"])
    learned_count = len(learned["ussgl_whitelist"]) + len(learned["fund_crosswalk"])
    lines = [
        "=" * 70,
        "  S8 KNOWLEDGE-FABRIC LEARNING LOOP — GL/journal slice",
        "=" * 70,
        "",
        f"  Input fixture: {LEARNING_FIXTURE.name}  ({p1['lines_in']} lines, 3 journals)",
        "",
        f"  {'metric':<26}{'PASS 1 (seed)':>16}{'PASS 2 (learned)':>18}",
        f"  {'-' * 60}",
        f"  {'lines in':<26}{p1['lines_in']:>16}{p2['lines_in']:>18}",
        f"  {'accepted (loaded)':<26}{p1['accepted']:>16}{p2['accepted']:>18}",
        f"  {'rejected':<26}{p1['rejected']:>16}{p2['rejected']:>18}",
        f"  {'mapping coverage':<26}{p1['mapping_coverage']:>16}{p2['mapping_coverage']:>18}",
        f"  {'all journals balanced':<26}{str(p1['all_journals_balanced']):>16}{str(p2['all_journals_balanced']):>18}",
        f"  {'LOAD READY':<26}{str(p1['load_ready']):>16}{str(p2['load_ready']):>18}",
        f"  {'reference data entries':<26}{seed_count:>16}{learned_count:>18}",
        "",
        f"  Pass 1 reject reasons : {p1['reject_reasons'] or '{}'}",
        f"  Pass 2 reject reasons : {p2['reject_reasons'] or '{}'}",
        "",
        "  WHAT THE LOOP DID",
        f"    - observed {p1['rejected']} reject(s) caused by incomplete reference data",
        f"    - SME confirmed they were valid; knowledge fabric grew by "
        f"{learned_count - seed_count} entr(y/ies)",
        f"    - recorded {learned_rows} correction row(s) in factory/knowledge/reject-taxonomy.md",
        f"    - re-ran the SAME input: rejects {p1['rejected']} -> {p2['rejected']}, "
        f"coverage {p1['mapping_coverage']} -> {p2['mapping_coverage']}, "
        f"load_ready {p1['load_ready']} -> {p2['load_ready']}",
        "",
        "  Artifacts written:",
        f"    - {LEARNED_REFERENCE.relative_to(REPO_ROOT)}",
        "    - factory/knowledge/reject-taxonomy.md  (LEARNED block)",
        "=" * 70,
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="S8 learning-agent demo")
    parser.add_argument("--json", action="store_true", help="emit machine-readable summary")
    args = parser.parse_args(argv)

    build_learning_fixture()
    seed = load_reference(BASE_REFERENCE)

    # PASS 1 — seed (incomplete) knowledge.
    apply_reference(seed)
    p1 = run_pass("seed")

    # LEARN — grow the knowledge fabric from the observed rejects.
    additions = grow_knowledge(seed, p1)
    learned_rows = update_taxonomy(additions)
    learned = load_reference(LEARNED_REFERENCE)

    # PASS 2 — learned knowledge, same input.
    apply_reference(learned)
    p2 = run_pass("learned")

    if args.json:
        print(json.dumps({"pass1": p1, "pass2": p2, "additions": additions}, indent=2))
    else:
        print(render(seed, learned, p1, p2, learned_rows))

    # The demo asserts the loop actually improved the outcome.
    improved = (
        p2["rejected"] < p1["rejected"]
        and p2["mapping_coverage"] > p1["mapping_coverage"]
        and p2["load_ready"]
        and not p1["load_ready"]
    )
    return 0 if improved else 1


if __name__ == "__main__":
    raise SystemExit(main())
